spring.application.name=spring_security

spring.security.user.name=isha
spring.security.user.password=1234


# Prevents the browser from sending the session cookie in cross-site requests
# Helps protect against CSRF attacks
server.servlet.session.cookie.same-site=strict

